-- MySQL Script generated by MySQL Workbench
-- Tue Dec 13 10:46:20 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema minePlay
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema minePlay
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `minePlay` DEFAULT CHARACTER SET utf8 ;
USE `minePlay` ;

-- -----------------------------------------------------
-- Table `minePlay`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minePlay`.`users` (
  `idusers` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idusers`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `minePlay`.`playlists`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minePlay`.`playlists` (
  `idplaylists` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `owner` VARCHAR(45) NULL,
  `viewers` VARCHAR(45) NULL,
  PRIMARY KEY (`idplaylists`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `minePlay`.`auxiliarPlaylist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minePlay`.`auxiliarPlaylist` (
  `idauxiliarPlaylist` INT NOT NULL AUTO_INCREMENT,
  `idPlaylist` INT NOT NULL,
  `idUser` INT NOT NULL,
  PRIMARY KEY (`idauxiliarPlaylist`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `minePlay`.`grupos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minePlay`.`grupos` (
  `idgrupos` INT NOT NULL AUTO_INCREMENT,
  `owner` VARCHAR(45) NULL,
  `integrantes` VARCHAR(45) NULL,
  PRIMARY KEY (`idgrupos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `minePlay`.`auxiliarGrupos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minePlay`.`auxiliarGrupos` (
  `idauxiliarGrupos` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `idUser` INT NOT NULL,
  `idGrupo` INT NOT NULL,
  PRIMARY KEY (`idauxiliarGrupos`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
